name: one_id
description: This is package for get user info with id.egov.uz
version: 0.0.8
homepage: https://github.com/Marufjonoff/one_id
authors:
  - Creator <marufjonovobidjon91@gmail.com>

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # this package only support Android and IOS support
  webview_flutter: ^3.0.4

  # this is package for server data
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg